#!/bin/sh
pluginpath="$(dirname "$(readlink -f $0)")"
ln -svf "$pluginpath/shrc" "$HOME/.shrc"
ln -svf "$pluginpath/zshrc" "$HOME/.zshrc"
ln -svf "$pluginpath/bashrc" "$HOME/.bashrc"
ln -svf "$pluginpath/profile" "$HOME/.profile"
mkdir -pv "$HOME/.profile.d"

ln -svf "$pluginpath/logout" "$HOME/.bash_logout"
ln -svf "$pluginpath/logout" "$HOME/.zlogout"

if ! [ -d "$HOME/.oh-my-zsh" ] && [ "zsh" = "$(basename "$SHELL")" ]; then
    rm -rf "$HOME/.oh-my-zsh"
    git clone https://github.com/robbyrussell/oh-my-zsh.git "$HOME/.oh-my-zsh"
fi
