#!/bin/sh
pluginpath="$(dirname "$(readlink -f $0)")"
ln -svf "$pluginpath/shrc" "$HOME/.shrc"
ln -svf "$pluginpath/shalias" "$HOME/.shalias"
ln -svf "$pluginpath/zshrc" "$HOME/.zshrc"
ln -svf "$pluginpath/bashrc" "$HOME/.bashrc"
ln -svf "$pluginpath/profile" "$HOME/.profile"
mkdir -pv "$HOME/.profile.d"

ln -svf "$pluginpath/logout" "$HOME/.bash_logout"
ln -svf "$pluginpath/logout" "$HOME/.zlogout"

